### PR TITLE
Create Dijkastra's Algorithm

### PR DESCRIPTION
**Pull request by Ishaan28malik**
Dijkatra's Algorithm for shortest path searches.

### CODE REVIEW

**Comment by abranhe** [comment]
Please include the `.cpp` extension and it must be in lower case letter

**Comment by Ishaan28malik** [comment]
ok

**Comment by Ishaan28malik** [comment]
done pls chk

**Comment by abranhe** [comment]
This pull request won't be merged :( because of Dijkstra's algorithm, its already implemented https://github.com/AllAlgorithms/cpp/blob/master/graphs/dijkstra.cpp

**Pull request closed without merging**
